Issues #9, #10, #11, #12, and #13 - experimental rewrite
gabor-meszaros/reporchestrator pull request #14
Opened 2019-09-11 16:41 UTC by sdrees

This pull request is quite large, I know, but it is provided as a jump start into enhanced future development support.

The `README.md` changes should give some overview of the content of this changeset.

Any feedback very welcome and thank you for starting this interesting project!

2019-09-11 18:50 UTC, gabor-meszaros commented
Thank you very much for this very decent PR. I have already seen that I'll learn a lot from it.

Currently, I am installing the dependencies, and then I'll try to run the tests and the linters on my local machine. As soon as I can make it work, I'll merge it.

I'll be busy tomorrow, but Friday or latest Saturday, I'll share the results.

Thank you again! 👍

2019-09-13 18:22 UTC, gabor-meszaros requested changes
I really like your new design, especially the config/model combo which made the tests easy to setup and understand. I think it is a solid start for the planned features.

One test fails at the first execution which needs to be fixed before the merge. It is easy to fix, we just don't need to expect a call (or sightly change the state that we test). :)

The other comments are mostly comments for myself.

Again... a very well thought out implementation, thank you for contributing to this project. 👍

2019-09-13 18:22 UTC, gabor-meszaros commented on tests/test_config.py
> +    rm_mock.assert_called_with(a_dir, ignore_errors=True)
This test failed for me on the first test run because the ```foo``` directory hasn't created yet therefore the ```rmtree``` is not called.

As soon as we merge this PR, I'll check how can we clean up the test environment between tests. If I understand correctly some tests are depend on the external ```foo``` directory, so the test result depends on the order of the execution of the test cases. It will be a good exercise for me. 👍

2019-09-13 18:22 UTC, gabor-meszaros commented on tests/test_model.py
> +    assert m in ("a", "b")
It is not easy to test these distributions. If I understand correctly, here the ```m``` can be generated by any distributions, the test will pass. Anyway, I think it is a good start for testing it, so no need to change anything. 👍

2019-09-13 20:03 UTC, sdrees commented on tests/test_config.py
> +    rm_mock.assert_called_with(a_dir, ignore_errors=True)
I will push a change - ideally in these tests no actual writes were planned, I assume I have to mock the ˋ os.path.isfile(a_dir)ˋ call here first ... thanks for checking and sorry for any inconveniience

2019-09-14 05:52 UTC, sdrees commented on tests/test_model.py
> +    assert m == "a"
Looking at this repetition, I will add a small rewrite in the amending commit.

2019-09-14 05:59 UTC, sdrees commented on reporchestrator.py
> +    cfg["developer_data"] = [
We should not overwrite any mixin contribution to `developer_data` and `developers`, but maybe check for consistency only (length and `team_size`

2019-09-14 06:02 UTC, sthagen reviewed
I will change three or more code locations and amend the PR. Thanks for taking the time to review and spotting a bug 👍

2019-09-14 16:37 UTC, sdrees commented
@gabor-meszaros: I made these changes twice b.t.w - that is how I was convinced to forbid empty repo_dir 😁 my changes were disappearing again and again and the editor told me the VCS root is wrong ... a fool with a tool is just a fool with a tool ... now I have tests write to temporary storage and check more interesting outcomes - and they are executing on my machine sequentially in under one second.
Maybe before running them in parallel (later), we will have to revisit the random selector tests but then maybe it is better to hand over a distribution itself instead of triggering the implementation by magic keywords ... hope you enjoy the reviewing as I did the coding (minus the `{"repo_dir": ""}` experience.

2019-09-15 14:49 UTC, gabor-meszaros commented
@sdrees I did enjoy the review. :) Thank you for fixing the bug and to further improve the test implementation. 👍 Let's merge this!

2019-09-15 14:50 UTC, merged